#ifndef __CONSOLE_H__
#define __CONSOLE_H__

/*
        Ouais ma vie est passionnante pour avoir écrit tout ça à la main.
*/

// Caractère d'échappement.
#define CONSOLE_ESC "\x1B"

// Liste des codes d'échappement, ne pas les utiliser en tant que tels mais favoriser les combos, par exemple CONSOLE_FG_WHITE pour écrire en blanc.
#define CONSOLE_CODE_RESET      "0"
#define CONSOLE_CODE_FG_BLACK   "30"
#define CONSOLE_CODE_FG_RED     "31"
#define CONSOLE_CODE_FG_GREEN   "32"
#define CONSOLE_CODE_FG_YELLOW  "33"
#define CONSOLE_CODE_FG_BLUE    "34"
#define CONSOLE_CODE_FG_MAGENTA "35"
#define CONSOLE_CODE_FG_CYAN    "36"
#define CONSOLE_CODE_FG_WHITE   "37"
#define CONSOLE_CODE_BG_BLACK   "40"
#define CONSOLE_CODE_BG_RED     "41"
#define CONSOLE_CODE_BG_GREEN   "42"
#define CONSOLE_CODE_BG_YELLOW  "43"
#define CONSOLE_CODE_BG_BLUE    "44"
#define CONSOLE_CODE_BG_MAGENTA "45"
#define CONSOLE_CODE_BG_CYAN    "46"
#define CONSOLE_CODE_BG_WHITE   "47"

// Retire tous les attributs d'échappement.
#define CONSOLE_RESET CONSOLE_ESC"["CONSOLE_CODE_RESET"m"

#define CONSOLE_FG_BLACK   CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK"m"
#define CONSOLE_FG_RED     CONSOLE_ESC"["CONSOLE_CODE_FG_RED"m"
#define CONSOLE_FG_GREEN   CONSOLE_ESC"["CONSOLE_CODE_FG_GREEN"m"
#define CONSOLE_FG_YELLOW  CONSOLE_ESC"["CONSOLE_CODE_FG_YELLOW"m"
#define CONSOLE_FG_BLUE    CONSOLE_ESC"["CONSOLE_CODE_FG_BLUE"m"
#define CONSOLE_FG_MAGENTA CONSOLE_ESC"["CONSOLE_CODE_FG_MAGENTA"m"
#define CONSOLE_FG_CYAN    CONSOLE_ESC"["CONSOLE_CODE_FG_CYAN"m"
#define CONSOLE_FG_WHITE   CONSOLE_ESC"["CONSOLE_CODE_FG_WHITE"m"

#define CONSOLE_BG_BLACK   CONSOLE_ESC"["CONSOLE_CODE_BG_BLACK"m"
#define CONSOLE_BG_RED     CONSOLE_ESC"["CONSOLE_CODE_BG_RED"m"
#define CONSOLE_BG_GREEN   CONSOLE_ESC"["CONSOLE_CODE_BG_GREEN"m"
#define CONSOLE_BG_YELLOW  CONSOLE_ESC"["CONSOLE_CODE_BG_YELLOW"m"
#define CONSOLE_BG_BLUE    CONSOLE_ESC"["CONSOLE_CODE_BG_BLUE"m"
#define CONSOLE_BG_MAGENTA CONSOLE_ESC"["CONSOLE_CODE_BG_MAGENTA"m"
#define CONSOLE_BG_CYAN    CONSOLE_ESC"["CONSOLE_CODE_BG_CYAN"m"
#define CONSOLE_BG_WHITE   CONSOLE_ESC"["CONSOLE_CODE_BG_WHITE"m"

// Lettres noires sur fond...
#define CONSOLE_BLACK_ON_BLACK   CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_BLACK"m"
#define CONSOLE_BLACK_ON_RED     CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_RED"m"
#define CONSOLE_BLACK_ON_GREEN   CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_GREEN"m"
#define CONSOLE_BLACK_ON_YELLOW  CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_YELLOW"m"
#define CONSOLE_BLACK_ON_BLUE    CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_BLUE"m"
#define CONSOLE_BLACK_ON_MAGENTA CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_MAGENTA"m"
#define CONSOLE_BLACK_ON_CYAN    CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_CYAN"m"
#define CONSOLE_BLACK_ON_WHITE   CONSOLE_ESC"["CONSOLE_CODE_FG_BLACK";"CONSOLE_CODE_BG_WHITE"m"

#endif